title: Pir2 team
url: http://www.pps.univ-paris-diderot.fr/pi.r2/
destination: _site
disqus: clarusblog
authors:
  claret:
    name: Guillaume Claret
    position: PhD student
    website: http://guillaume.claret.me/
    email: guillaume@claret.me
    twitter: guillaumeclaret
