title: PPS team
url: http://www.pps.univ-paris-diderot.fr/
destination: _site
disqus: pir2
posts_per_page: 3
authors:
  claret:
    name: Guillaume Claret
    picture: http://guillaume.claret.me/home/images/me.jpg
    position: PhD student
    website: http://guillaume.claret.me/
    email: guillaume@claret.me
    twitter: guillaumeclaret
