title: PPS team
url: http://www.pps.univ-paris-diderot.fr/
destination: _site
disqus: pir2
posts_per_page: 3
authors:
  claret:
    name: Guillaume Claret
    picture: http://www.gravatar.com/avatar/5b345cf37d25e00f1e20f1f1154237f4.png
    position: PhD student
    website: http://guillaume.claret.me/
    email: guillaume@claret.me
    twitter: guillaumeclaret
